### ISSUE TITLE
Change in Waze's Data

### ISSUE THREAD

**Issue by TheDravenator** [TheStalwart/waze2gpx#1]
It appears as though Waze has, at some point, changed their formatting. The trip data is now kept in the second file instead of the third one. Even so, when I attempt to use it, the GPX data thinks I was in Antarctica for some reason.

**Comment by TheStalwart** [comment]
@TheDravenator thanks for the report. Indeed, compared to data i exported in August - format has changed slightly. Looks like an easy fix though.

However, in my case all data is still in account_activity_3.csv file.

```
-a----        20.09.2024     01:22              0 account_activity_1.csv
-a----        20.09.2024     01:22              0 account_activity_2.csv
-a----        20.09.2024     01:22        1102108 account_activity_3.csv
-a----        20.09.2024     01:22            690 account_info.csv
-a----        20.09.2024     01:22        2212800 image_2_1.png
```

I'd appreciate if you share your data export - my email can be found on GitHub profile

**Comment by TheStalwart** [comment]
@TheDravenator  Added support for new coordinate format in ba14d0fcde62ab08ac0b12c2088c722babc6e9d3

As for data in files other than account_activity_3.csv - i cannot reproduce with my Waze account. I need someone to share an archive i can investigate.

**Comment by TheStalwart** [comment]
Solved the problem of figuring out which of the account_activity_* files contains data by implementing multiple file upload. Just upload all CSV files and the app will extract trips from all of them.

7a72fbb3c03e297cf89fcc77a739e15151008bea
